### PR TITLE
Fix unused dependencies

### PR DESCRIPTION
**Pull request by arichiardi**
It removes unused or already provided dependencies from build.boot and core.clj

### CODE REVIEW

**Comment by arichiardi** [comment]
@flyboarder is there a `SNAPSHOT` version up with this?

**Comment by burn2delete** [comment]
@arichiardi not yet, I will push it today 😄

**Comment by arichiardi** [comment]
Perfect! Thanks a lot!

**Comment by burn2delete** [comment]
@arichiardi version `1.3.0` is on clojars 😸

**Pull request merged**
